### ISSUE TITLE
3 new samples that don't work

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#157]
Directory "/Ramit Bhalla" in the repository.

**Comment by kisselef** [comment]
1. There is no problem with ccextractor for *.wtv files. Metadata says that they are both ~30 min long, but in fact they are smaller. Since ccextractor handles this situation correctly - detects premature end of file, outputs CC and doesn't crash, I think everything is fine with it.
2. Detecting TS/PS without falling through fixed https://github.com/kisselef/ccextractor/tree/feature-ts-ps-detection, but server is down, so I will create a pull request after regression tests.

**Comment by kisselef** [comment]
There was PS sync byte 0x000001BA inside TS stream, so after source was detected as ts, it was re-detected as PS
https://github.com/CCExtractor/ccextractor/pull/171
