### ISSUE TITLE
Captions not detected in WTV file

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#203]
The repository contains this directory: /MurdochMisteries_nocaptions

There's a file there for which we find no captions but reports say that MCEBuddy does.

I'm assigning this to Anshul since he's doing stream work :-)

**Comment by anshul1912** [comment]
Unable to see caption using MCEBUddy on same video, what version of MCE Buddy they are using?

**Comment by afeldspar** [comment]
The main screen of the program says it's "MCEBuddy 2.3, Release 13".  I can provide the log of the conversion, and the complete WTV file if that's desired, but I'm just starting with github, so it may take me a little bit to figure out how.

**Comment by afeldspar** [comment]
This should be the log file for the successful conversion through MCEBuddy.  One thing I notice is that CCExtractor is getting a transport stream to work with, rather than the original file...

[conversion log](https://drive.google.com/file/d/0BxmJEtyy3_20cDlvTXlhZ3dURzRQOENHcDNBZlVFM0lrRTIw/view?usp=docslist_api)

And this should be the actual caption file (extracted from the complete .wtv file, which is of course very large, so if it's needed, I'll have to figure out some way to upload somewhere...)

[captions](https://drive.google.com/file/d/0BxmJEtyy3_20cTRGN2NybWdUMzR2aVBrODg1czBzYVJMLWFv/view?usp=docslist_api)

**Comment by cfsmp3** [comment]
@afeldspar is this still a valid report (for current git version)?

**Comment by afeldspar** [comment]
Unfortunately, I had a computer crash and my recording setup has radically
changed.  I should be able to migrate some data and check whether it works,
but it may take a while.

**Comment by cfsmp3** [comment]
OK, closing for now. Feel free to comment when/if you are able to give it a try in the future.
