### ISSUE TITLE
Here's a quandary: 608 captions in Korean

### ISSUE THREAD

**Issue by SWalkerTTU** [CCExtractor/ccextractor#409]
Some time back I downloaded a TS of the Korean music show "Music Bank" on KBS2 (a clip from "인기가요" of Crayon Pop performing "Dancing Queen") and at the time of recording (late 2012) KBS2 was using 608 captions, as ccextractor 0.81 could pull that data out into BIN format. However, 0.81 could not convert it to SRT. hexdump -C shows readable ASCII text (the English words from the song) so sensible captions are able to be extracted. 

Here's the extracted BIN, zipped:
[DancingQueen.bin.zip](https://github.com/CCExtractor/ccextractor/files/417044/DancingQueen.bin.zip)

I've consulted the binary file format documentation, so I now have some idea of what's going on, but perhaps mentally parsing the binary file is not the most efficient way to approach this. The documentation also mentions the cc_type and cc_valid fields in the first byte of three-byte caption groups, but doesn't say much past that.

**Comment by cfsmp3** [comment]
We need the TS file. .bin are only useful when the problem is with the 608 decoder itself.

Could you upload the .TS to dropbox, google drive, or any other host? (decent one, not one of those that require registration or payment to download at decent speeds).

Reopen when you have a link and we'll be happy to take a look.
