### ISSUE TITLE
WEBVTT header lacks empty newline

### ISSUE THREAD

**Issue by atrottmann** [CCExtractor/ccextractor#439]
Using the WEBVTT files generated by ccextractor in a HTML5 video context, I have noticed that the first entry is skipped by the browser. Apparently this is the case because it expects an empty line between the WEBVTT header and the first subtitle entry.

Changing line 60 of src/lib_ccx/ccx_encoders_common.c to include a second pair of \r\n appears to fix the problem:

  static const char *webvtt_header = "WEBVTT\r\n\r\n";

Kind regards,
Andreas Trottmann

**Comment by cfsmp3** [comment]
Adding that \r\n is the correct fix but not there - otherwise we cannot add more data to the header before the body starts.  We're not doing it for now, but definitely we don't want to make it impossible by adding the header terminator in the same place the file signature is.

Anyway, fixed now in master.
