### ISSUE TITLE
[CEA-708] [Timing] Catchable bug with timing

### ISSUE THREAD

**Issue by Izaron** [CCExtractor/ccextractor#641]
It is known that timing in our CEA-708 is different from the timing of CEA-708 in video player with a difference of a second or so and in general it's not critical error.
But sometimes the timing differs a lot - end of the time goes ahead ~10 seconds or so in different examples. This always happens due to this bug where window is undefined (**decoder->current_window == -1**) and it's col_count too: [line](https://github.com/Izaron/ccextractor/blob/7078f1015024d68115d8659a9187224d0d7ad363/src/lib_ccx/ccx_decoders_708_output.c#L122) (and line 129). It may be a one line fix or maybe hell with codecs, but I must sleep and somewhere else, so if you want we can fix it together.

**Comment by cfsmp3** [comment]
GSoC qualification: This issues gives 2 points.

**Comment by shucon** [comment]
@Izaron I was about to open an issue for the same , but found it here , maybe I could start working on this.

**Comment by cfsmp3** [comment]
Definitely, go ahead :-)

**Comment by gray-v** [comment]
Yo can I get a sample for this one?

**Comment by MatejMecka** [comment]
Sample?

**Comment by thetransformerr** [comment]
Hi all and @cfsmp3 , 
After searching and working for a long time , I have few reasons that might be responsible for this timing issues, although the current base for 708 is already following up to 90-95% standards laid down by CEA-708 specifications, problems mostly arise due to lack on video part , like missing PMT, incorrect packet encoding , there are few scopes in code where we can handle them , 

Acc. to specs,

> whenever a window is to be deleted ,  If any one of the deleted windows is current window, the value of current window ID becomes "unknown/uninitialized" , and characters following this command do not go to any window until a SetCurrentWindow or DefineWindow command is received for this service.

- so after analysing videos and report from this folder https://drive.google.com/drive/folders/0B_61ywKPmI0Ta2diT3l0eTlHc2c , one or one of the many reasons is whenever a current window is deleted which is visible , its content are flushed to screen however the following characters causes the issues until a new window is set current window by either SetCurrentWindow or DefineWindow command.

So the line referenced in first post of this issue , is this https://github.com/CCExtractor/ccextractor/blob/25a8b53ff55f904f29e4810bdaedd4f154567677/src/lib_ccx/ccx_decoders_708_output.c#L137 
and this condition is true whenever following of these conditions are true:

https://github.com/CCExtractor/ccextractor/blob/25a8b53ff55f904f29e4810bdaedd4f154567677/src/lib_ccx/ccx_decoders_708_output.c#L222

in this line , although we check screen content but current_window many times have value -1
https://github.com/CCExtractor/ccextractor/blob/25a8b53ff55f904f29e4810bdaedd4f154567677/src/lib_ccx/ccx_decoders_708.c#L1115

which causes above mentioned exception and also we cannot ignore content without defined windows, as I have tested we miss captions.

Therefore either we can store that data until a new window is defined or we can flush screen data before removing window.

This is just one instance , similar solution might be needed for handling this issue in other case .

in following patch I have done modification,

https://github.com/thetransformerr/ccextractor/blob/ae73f147a545003ea58c94925cf14891ad43d8dc/src/lib_ccx/ccx_decoders_708.c#L1206

**Comment by thetransformerr** [comment]
after this modification there is one similar message when I use following command on video ande.ts from folder https://drive.google.com/drive/folders/0B_61ywKPmI0Ta2diT3l0eTlHc2c 

`ccextractor ande.ts -svc all`

__dtvcc_handle_G0: Window has to be defined first_

this happens from here:
https://github.com/thetransformerr/ccextractor/blob/ae73f147a545003ea58c94925cf14891ad43d8dc/src/lib_ccx/ccx_decoders_708.c#L1389

Although this doesn't look like other one above , I would really like to know , if we can set window ourselves before we receive command from stream , rather then ignoring the leftover data.

this can solve issues related to lost of data where as doing this would be deviation from standard EIA_708
