### ISSUE TITLE
ctrl-c not working in linux

### ISSUE THREAD

**Issue by cfsmp3** [CCExtractor/ccextractor#661]
ctrl-c (sigint) is not working on the linux version, which is quite annoying.

**Comment by Izaron** [comment]
After removing this line all is OK - https://github.com/CCExtractor/ccextractor/blob/master/src/ccextractor.c#L154
But don't sure if we should just *remove* this line without understanding.

**Comment by saurabhshri** [comment]
@Izaron Instead of deleting it, I think it will be better to appropriately handle it. For example, if we want to terminate it ASAP on receiving SIGINT, we can do this -> (https://github.com/CCExtractor/ccextractor/compare/master...saurabhshri:patch-2). 

@cfsmp3 Please have a look at the above commit. Does this seem okay to you?

**Comment by cfsmp3** [comment]
Both solutions are OK. The problem is that we're mixing different (and incompatible) ways to setup handlers. I've solved it by having 3 handlers that are setup in the same way.
