### ISSUE TITLE
[CEA-708] Is there a way to extract subtitles

### ISSUE THREAD

**Issue by fsh240led** [CCExtractor/ccextractor#677]
The others are extracted without problems
But the video below is not extract
https://docs.google.com/uc?id=0B42jO8cBUe6baEtqLTNkRnExbVk&export=download

PotPlayer displays subtitles
http://i.imgur.com/SX9KApM.png

**Comment by cfsmp3** [comment]
Are yo sure you aren't using an external subtitle file? I just installed
potplayer for this and it says there's no subtitles available.

**Comment by fsh240led** [comment]
Preferences required

Preferences(F5) -> Filter Control -> Video Decoder -> Built-in codec/DXVA settings -> Enable Closed Captioning (Check)

**Comment by cfsmp3** [comment]
I'm probably missing some fonts, this is what a see after enabling CC. 

![sbsplus](https://cloud.githubusercontent.com/assets/5949913/22720320/e8414a66-ed5e-11e6-81e9-34209d27298e.png)

**Comment by fsh240led** [comment]
korean font download link
[http://ko.cooltext.com/Fonts-Unicode-Korean](url)

**Comment by fsh240led** [comment]
[[img]http://i.imgur.com/SX9KApM.png[/img]](url)

**Comment by fsh240led** [comment]
`[img]http://i.imgur.com/SX9KApM.png[/img]`

**Comment by cfsmp3** [comment]
Assigning to @Izaron since he was the last one looking into Korean.

**Comment by cfsmp3** [comment]
GSoC qualification: 3 points.

**Comment by Izaron** [comment]
@fsh240led Are this output **at 00:09** from the other video player is incorrect also in comparing with PotPlayer? Can you confirm it?

![default](https://cloud.githubusercontent.com/assets/5406399/22783469/034ae50e-eedd-11e6-8fcb-bd1b77a0baad.png)

@cfsmp3 and @AlexBratosin2001 (since you're PTS man)
Problem is there: https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/stream_functions.c#L307
Can you give me specs about this binary stream, when `(nextheader[7]&0xC0) == 0xC0`? Maybe there just problem with hexadecimal hardcoded constants.

**Comment by fsh240led** [comment]
It is an unknown words
It should be output as

<img src="http://i.imgur.com/SX9KApM.png">

**Comment by mahalwal** [comment]
@fsh240led Can you tell which font are you using from this link? ( http://ko.cooltext.com/Fonts-Unicode-Korean ) I tried Batang(che), Gungsuh(che) and they are still giving random characters.

**Comment by MatejMecka** [comment]
@fsh240led Can you tell me with which command did you got this subtitles?

**Comment by MakarovGCI2018** [comment]
The problem was that when we tried to process this file we got error "Window has to be defined" because decoder->current_window == -1;
https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_708.c#L1375
So I found out that in ccx_decoders_708.c we had a condition which wasn't impossible according to authors comment but here that condition returned true which crashed ccextractor extracting captions and made ret = 0; which is No captions found in Input error. 
Here is the problem:
https://github.com/CCExtractor/ccextractor/blob/master/src/lib_ccx/ccx_decoders_708.c#L1728
And the obvious fix is to change:
_dtvcc_decoders_reset(dtvcc);
return;
to
dtvcc->current_packet_length = len;
* Note: I think it would be better also to delete comment("Is this possible") cause as we see it is possible.

After all those changes ccextractor is able to extract captions from this file.

**Comment by cfsmp3** [comment]
OK so it's good research here... but let's not be happy with that, we need to find out what's actually going on. 

if (dtvcc->current_packet_length != len) // Is this possible?

So there dtvcc->current_packet_length is how much data we have for that packet.
len is the size length according to the packet header.

So we have 3 possibilities:
a) We have more data than the declared packet length. If yes - what's that data, where did it come from, what is it for? Can we ignore it?
b) We have LESS data than the declared packet length. This is really not good, we can't process the packet at all (we would read out of bounds)
c) They match, which is the expected thing, but we know that's not the case here.

So first - let's check if it's a or b.

**Comment by cfsmp3** [comment]
That line:

int len = dtvcc->current_packet[0] & 0x3F; // 6 least significants bits

is correct. The packet header has 6 bits for the packet length and that mask gives you those 6 bits.

You may need to go over the actual specs to understand that code.

**Comment by PunitLodha** [comment]
What i found was that there is are extra 2 bytes (Both are always 0) after the stipulated len specified in the header

Example:-
Here in the header, len is specified as 22.
Number |  cc valid | cc type | cc data1 | cc data2
| --- | --- | --- | --- | --- |
.. | .. | .. | .. | .. 
3 | 1 | 3 | pkt header | pkt data 
4 | 1 | 2 | pkt data | pkt data 
5 | 1 | 2 | pkt data | pkt data 
6 | 1 | 2 | pkt data | pkt data 
.. | .. | .. | .. | .. 
13 | 1 | 2 | pkt data | pkt data 
14 | 1 | 2 | pkt data(should be padding) | pkt data(should be padding)
15 | 0 | 2 | pkt data(padding) | pkt data(padding)
16 | 0 | 2 | pkt data(padding) | pkt data(padding) 
.. | .. | .. | .. | .. 

While parsing line 13, current_packet_length also becomes 22, which means after that everything should be padding(cc_valid = 0)
But on line 14 we have cc_valid = 1, which leads to it being parsed and current_packet_length becoming 24, ie current_packet_length = len +2

I guess we can safely ignore the two bytes, and change,
``` c
if (dtvcc->current_packet_length != len) // Is this possible?
{
    _dtvcc_decoders_reset(dtvcc);
    return; 
}

```
to
``` c
if (dtvcc->current_packet_length != len) 
{
    // Extra padding data, can be ignored
    dtvcc->current_packet_length = len; 
}
```
Should i go ahead with the change?

**Comment by cfsmp3** [comment]
@PunitLodha Good research.
Well, give it a go and see if it makes things better or worse.

**Comment by ValZapod** [comment]
> I'm probably missing some fonts, this is what a see after enabling CC.

That is just a bug in Potplayer's locale stuff, since there is no problem when you actually extract the srt with `ccextractorwinfull.exe -svc 1[EUC-KR] Sample.ts
`
For posterity on latest 0.93: 
[Sample.p401.svc01.srt.txt](https://github.com/CCExtractor/ccextractor/files/7173659/Sample.p401.svc01.srt.txt)
