### ISSUE TITLE
mp4 files not automatically detected

### ISSUE THREAD

**Issue by anshul1912** [CCExtractor/ccextractor#69]
history: discussion regarding this started https://github.com/CCExtractor/ccextractor/pull/58/files#r14395363

**Comment by Akirato** [comment]
Is the issue that the mp4 is not always detected with the method right now?
In that case, File Signatures can be used. If the binary file contains "ftyp" (like ...ftyp) then it is "mp4". 
Try string file.mp4 | grep "ftyp"
"ftyp" is mp4's file signature.

**Comment by cfsmp3** [comment]
On Sun, Mar 8, 2015 at 4:07 PM, Nurendra Choudhary <notifications@github.com
> wrote:

> Is the issue that the mp4 is not always detected with the method right now?
> In that case, File Signatures can be used. If the binary file contains
> "ftyp" (like ...ftyp) then it is "mp4".
> Try string file.mp4 | grep "ftyp"
> "ftyp" is mp4's file signature.
>
It's not that simple... the mp4 can contain different box headers, ftyp is
not guaranteed at all to be at the beginning of the file. In general, the
thing is that there's a conflict and that other types are matching because
mp4 does (in the code). Changing the detection order that alters the misses
but doesn't solve them completely.

**Comment by Akirato** [comment]
This is the order right now: ASF,WTV,HEX,RCWT,TS,PS,MP4 ( https://github.com/CCExtractor/ccextractor/pull/58/files#r14395363 )
I think bash command "file <file-name>" can be used. This will just decide the file type directly.
Thus, there would not be any need for an order.

**Comment by cfsmp3** [comment]
On Mon, Mar 9, 2015 at 6:15 AM, Nurendra Choudhary <notifications@github.com
> wrote:

> I think bash command "file " can be used. This will just decide the file
> type directly.
>
We cannot rely on any external program. First because CCExtractor is
portable and there's no "file" in Windows. Second, because we need to know
what's going on. Why would you think "file" is more reliable than
CCExtractor? Most likely if you run it in all our samples there will be
some problems too.

**Comment by Akirato** [comment]
Hey, what I actually meant by using "file" was to use its algorithm but I found out that this too depended upon the signatures. So, its of no use :( .
I checked out the present system CCExtractor is following and that the problem is the ctx->stream_mode gets PS and so it cannot get MP4. I also saw that a similar thing is happening with "TiVo", right. So, can the MP4 be handled in the same way as TiVo.

**Comment by cfsmp3** [comment]
I've given MP4 detection priority over PS. Both detections are weak (there just need to be a match of a 4 byte sequence somewhere close to the beginning of the file) and could use improvement (for example count the number of possible mp4 boxes vs possible PACK headers), but let's see how this works for now.
