### ISSUE TITLE
[BUG]   subtitles extract but no delay added

### ISSUE THREAD

**Issue by tjmorris11** [CCExtractor/ccextractor#779]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

CCExtractor version (using the --version parameter preferably) : **X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/CCExtractor/ccextractor/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/CCExtractor/ccextractor/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have used the latest available version of CCExtractor to verify this issue exists.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [x] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

**Necessary information**
- Is this a regression (did it work before)? [x] NO | [ ] YES - *please specify the last known working version*
- What platform did you use? [x] Windows - [ ] Linux - [ ] Mac
- What where the used arguments? `-delay

**Video links**
https://www.dropbox.com/s/omar8vkh6ncgeq1/Judge%20Judy%29.ts?dl=0

Please make the affected input file available for us (no screenshots, those don't help!). Public links to Dropbox, Google Drive, etc, are all fine. If it is not possible to make it available publicly, send us a private invitation (both Dropbox and Google Drive allow that). In this case we will download the file and upload it to the private developer repository.

Do *not* upload your file to any location that will require us to sign up or endure a wait list, slow downloads, etc. If your upload expires make sure you keep it active somehow (replace links if needed). Keep in mind that while we go over all tickets some may take a few days, and it's important we have the file available when we actually need it.

**Additional information**
--version .85b  ,  even happens with CCExtractorGUI  --- subtitles extract OK.... but options not working -- when using the GUI, i set a delay   but there is no change in the timings of the srt...
 have uploaded  .TS file that I used 

PS: Make sure you set an alert in GitHub so you get notifications about your ticket. We may need to ask questions and we do everything inside GitHub's system.

**Comment by Hallikas** [comment]
I can confirm this. Delay parameter does not seem to work.

semi@convert1:/data/Elokuvat.ok/z_new# ccextractor **-delay 1400** -gt -utf8 -dvblang fin -noteletext -nocodec teletext -nodvbcolor --nofontcolor --notypesetting -trim -srt ts-stream-with-single-subs.ts -o output.srt
CCExtractor 0.85, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc
--------------------------------------------------------------------------
Input: ts-stream-with-single-subs.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: GOP (forced)] [Debug: No] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [**Delay: 1400**] [Trim lines: Yes]
[Add font color data: No] [Add font typesetting: No]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------
Opening file: ts-stream-with-single-subs.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
Creating output.srt
  1%  |  00:33^Csemi@convert1:/data# head -2 *.srt
1
**00:00:00,124** --> 00:00:03,569
semi@convert1:/data#

**Comment by cfsmp3** [comment]
Fixed, reopen if the issue appears again.

**Comment by tjmorris11** [comment]
hi ...thanks for update 
    
    1.  the problem is Not fixed..
    2. how do I re-open
    thank you
    Trevor
    
    
    On 12/6/2017 2:16 AM, Carlos Fernandez
      Sanz wrote:
    
    
      Fixed, reopen if the issue appears again.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CCExtractor/ccextractor","title":"CCExtractor/ccextractor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CCExtractor/ccextractor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cfsmp3 in #779: Fixed, reopen if the issue appears again."}],"action":{"name":"View Issue","url":"https://github.com/CCExtractor/ccextractor/issues/779#issuecomment-349364880"}}}

**Comment by saurabhshri** [comment]
@tjmorris11 I just tested with the sample you've attached, and the delay parameter just worked fine. Here are the outputs : 

1. Without delay parameter : `./ccextractor Judge\ Judy\).ts`

```
522
00:31:37,120 --> 00:31:39,439
You'll notice when you do this that
the texture of the onions changes
``` 

2. With delay parameter : `./ccextractor Judge\ Judy\).ts -delay 1111`

```
522
00:31:38,231 --> 00:31:40,550
You'll notice when you do this that
the texture of the onions changes
```

Could you please tell the exact parameters you are using to set the delay?

**Comment by Hallikas** [comment]
I have that same problem. I have TS file with subtitles, that TS has delay itself, but ccextractor does not see that. That's why I need to add manual delay.

$ ffprobe Outlander_-_Matkantekijä_\(16\)_20171129_2135.subs.ts
ffprobe version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
Input #0, mpegts, from 'Outlander_-_Matkantekijä_(16)_20171129_2135.subs.ts':
  Duration: 00:53:34.20, **start: 144.786122**, bitrate: 10 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x403](fin): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)

$ mediainfo Outlander_-_Matkantekijä_\(16\)_20171129_2135.subs.ts
General
ID                                       : 1 (0x1)
Complete name                            : Outlander_-_Matkantekijä_(16)_20171129_2135.subs.ts
Format                                   : MPEG-TS
File size                                : 4.14 MiB
Duration                                 : 53mn 34s
Overall bit rate mode                    : Variable
Overall bit rate                         : 10.8 Kbps

Text
ID                                       : 1027 (0x403)
Menu ID                                  : 1 (0x1)
Format                                   : DVB Subtitle
Codec ID                                 : 6
Duration                                 : 53mn 34s
Language                                 : Finnish

Menu
ID                                       : 4096 (0x1000)
Menu ID                                  : 1 (0x1)
Duration                                 : 53mn 34s
List                                     : 1027 (0x403) (DVB Subtitle, Finnish)
Language                                 : Finnish
Service name                             : Service01
Service provider                         : FFmpeg
Service type                             : digital television

$ ccextractor -debug -delay 14478 -gt -utf8 -dvblang fin -noteletext -nocodec teletext -nodvbcolor --nofontcolor --notypesetting -trim -srt Outlander_-_Matkantekijä_\(16\)_20171129_2135.subs.ts -o _subs  -debugdvbsub                 CCExtractor 0.85, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc

--------------------------------------------------------------------------

Input: Outlander_-_Matkantekijä_(16)_20171129_2135.subs.ts
[Extract: 1] [Stream mode: Autodetect]
[Program : Auto ] [Hauppage mode: No] [Use MythTV code: Auto]
[Timing mode: GOP (forced)] [Debug: Yes] [Buffer input: No]
[Use pic_order_cnt_lsb for H.264: No] [Print CC decoder traces: No]
[Target format: .srt] [Encoding: UTF-8] [Delay: 14478] [Trim lines: Yes]
[Add font color data: No] [Add font typesetting: No]
[Convert case: No] [Video-edit join: No]
[Extraction start time: not set (from start)]
[Extraction end time: not set (to end)]
[Live stream: No] [Clock frequency: 90000]
[Teletext page: Autodetect]
[Start credits text: None]

-----------------------------------------------------------------

Opening file: Outlander_-_Matkantekijä_(16)_20171129_2135.subs.ts
File seems to be a transport stream, enabling TS mode
Analyzing data in general mode
  1027 |   6 (  6) | MPEG-2 private data

DVBSUB - LANGUAGE "fin" FOUND
  MPEG-2 private data stream [0x06]  -  PID: 1027
PES header length: 14 (14 verified)  Data length: 11
DVBSUB - PTS: 13030751, FTS: 0, SEGMENT TYPE: 16, SEGMENT LENGTH: 2, PAGE STATE 1
  0%  |  00:01
PES header length: 14 (14 verified)  Data length: 2827
DVBSUB - PTS: 13149587, FTS: 1320, SEGMENT TYPE: 16, SEGMENT LENGTH: 8, PAGE STATE 2, REGION 0 ADDED
DVBSUB - PTS: 13149587, FTS: 1320, SEGMENT TYPE: 17, SEGMENT LENGTH: 16, REGION 0 WIDTH: 270, REGION 0 HEIGHT: 54
^C
$ head _subs
1
00:00:01,320 --> 00:00:01,599
Aiemmin... - Isä!

2
00:00:01,600 --> 00:00:04,039
Kuka tuo nainen on?
- Isä?

... And it does not matter what ever value I put on -delay

ccextractor --version
CCExtractor 0.85, Carlos Fernandez Sanz, Volker Quetschke.
Teletext portions taken from Petr Kutalek's telxcc

--------------------------------------------------------------------------

CCExtractor detailed version info
        Version: 0.85
        Git commit: c78db1dd248f86232ca31d82c1d03bfbfb05f2e6
        Compilation date: 2017-12-05
        File SHA256: 93b86ab0dd11ab239ae3243e7cf35d36506a5354382b4216e2ecd4f743387d60

**Comment by cfsmp3** [comment]
@harrynull can you check it out? Most likely the delay needs to be added to a different branch of code as well - specifically, the DVB (that's European subtitles) one.

**Comment by harrynull** [comment]
@cfsmp3 I'll check.

**Comment by tjmorris11** [comment]
hi ... thanks for the reply
                            I have not explained my self very well. (
      and I have not  uploaded a good ".TS"example)
    
              Only some TV recordings have  subtitles that are out
        of sync ....
      
        and that is Not the fault of ccextractor
        it is the fault of the broadcaster
        generally 'live tv programs'
      
          so for those tv  live tv programs I want to add a delay
        with ccextractor
      
         the recording i uploaded was judge judy (even though Is in
          sync)
        
        i uploaded that one because it only 30 min program
        and should still be good for testing
        
      
           But delay function in ccextractor does not work for Any
        of my Tv recording(including Judge judy --testing purposes)
      
         does not work for ccextractor cli and gui
      
       Its possible that its an issue with my TS files  or maybe my
        hauppuage tv card
      
         its strange that i can not see any other reported delay
          issues in ccextractor blogs
      
    
    So if you could put a 5 second delay in Judge judy and see if the
      delay happens
    thanks... Trevor
    
    
    
    
    
    On 12/6/2017 7:36 AM, Saurabh Shrivastava wrote:
    
    
      @tjmorris11 I just tested with the
        sample you've attached, and the delay parameter just worked
        fine. Here are the outputs :
      
        Without delay parameter : ./ccextractor Judge\
            Judy\).ts
      
      522
00:31:37,120 --> 00:31:39,439
You'll notice when you do this that
the texture of the onions changes

      
        With delay parameter : ./ccextractor Judge\ Judy\).ts
            -delay 1111
      
      522
00:31:38,231 --> 00:31:40,550
You'll notice when you do this that
the texture of the onions changes

      Could you please tell the exact parameters you are using to set
        the delay?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CCExtractor/ccextractor","title":"CCExtractor/ccextractor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CCExtractor/ccextractor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@saurabhshri in #779: @tjmorris11 I just tested with the sample you've attached, and the delay parameter just worked fine. Here are the outputs : \r\n\r\n1. Without delay parameter : `./ccextractor Judge\\ Judy\\).ts`\r\n\r\n```\r\n522\r\n00:31:37,120 --\u003e 00:31:39,439\r\nYou'll notice when you do this that\r\nthe texture of the onions changes\r\n``` \r\n\r\n2. With delay parameter : `./ccextractor Judge\\ Judy\\).ts -delay 1111`\r\n\r\n```\r\n522\r\n00:31:38,231 --\u003e 00:31:40,550\r\nYou'll notice when you do this that\r\nthe texture of the onions changes\r\n```\r\n\r\nCould you please tell the exact parameters you are using to set the delay?"}],"action":{"name":"View Issue","url":"https://github.com/CCExtractor/ccextractor/issues/779#issuecomment-349457551"}}}

**Comment by harrynull** [comment]
>           But delay function in ccextractor does not work for Any
>        of my Tv recording(including Judge judy --testing purposes)
>         does not work for ccextractor cli and gui
The delay is set correctly if you manually set the delay parameter.
Note that the issue is fixed but the fixed version of CCExtractor has not been released yet. To make it work, you need to wait for the next release or compile it by yourself.

I have attached the latest version of CCExtractor for you. Try this one and see if it works.
[ccextractor.zip](https://github.com/CCExtractor/ccextractor/files/1533936/ccextractor.zip)

**Comment by tjmorris11** [comment]
well done &  thanks .....  what you sent me works.......
     I thought  ccextractor 8.5b was the latest, i down loaded it 
    earlier this morning and it failed 
    but what ever  version you sent me today  , works great....
     thanks again
    p.s.  what I had been doing, as a work around, I wrote a  app in
      .net to add delays  but that  just adds an extra layer
    PP.s    OOpps   I just noticed another problem    .......    
      OPTION -sc  OR --sentencecap   does Not work .... it should make
      every thing lowercase ( except first letter in a sentence)  BUT
      does not work in version .85b or the version yo sent me  ....  DO
      YOU WANT ME TO OPEN A NEW TICKET 
    
     cheers..........
    
    
    On 12/6/2017 2:25 PM, Null wrote:
    
    
      
              But delay function in ccextractor does not work for Any
   of my Tv recording(including Judge judy --testing purposes)
    does not work for ccextractor cli and gui

      
      The delay is set correctly if you manually set the delay
        parameter.
        Note that the issue is fixed but the fixed version of
        CCExtractor has not been released yet. To make it work, you need
        to wait for the next release or compile it by yourself.
      I have attached the latest version of CCExtractor for you. Try
        this one and see if it works.
        ccextractor.zip
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CCExtractor/ccextractor","title":"CCExtractor/ccextractor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CCExtractor/ccextractor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@harrynull in #779: \u003e           But delay function in ccextractor does not work for Any\r\n\u003e        of my Tv recording(including Judge judy --testing purposes)\r\n\u003e         does not work for ccextractor cli and gui\r\nThe delay is set correctly if you manually set the delay parameter.\r\nNote that the issue is fixed but the fixed version of CCExtractor has not been released yet. To make it work, you need to wait for the next release or compile it by yourself.\r\n\r\nI have attached the latest version of CCExtractor for you. Try this one and see if it works.\r\n[ccextractor.zip](https://github.com/CCExtractor/ccextractor/files/1533936/ccextractor.zip)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/CCExtractor/ccextractor/issues/779#issuecomment-349533464"}}}

**Comment by cfsmp3** [comment]
Yes, please open a new ticket if it's a different issue, thanks.
